from .main_page import MainPage
from .catalog_page import CatalogPage
from .product_page import ProductPage
from .login_admin_page import LoginAdminPage
from .register_page import RegisterPage
from .logout_admin_pages import LogoutAdminPages
from .home_page import HomePage
from .cart_page import CartPage
from .currency_switch_home import SwitchHomePage
from .currency_switch_catalog import SwitchCatalogPage
from .admin_product_new_pages import AdminProductNew
from .admin_delete_product_pages import AdminProductDelete
from .register_new_user_pages import RegisterNewUser
